init copy

diff --git a/columnstore-init b/columnstore-init
--- a/columnstore-init
+++ b/columnstore-init
@@ -17,14 +17,9 @@ S3_ACCESS_KEY_ID="${S3_ACCESS_KEY_ID:-fakeaccesskeyid}"
 S3_SECRET_ACCESS_KEY="${S3_SECRET_ACCESS_KEY:-fakesecretaccesskey}"
 
 # Set Credential Defaults If Missing
-ADMIN_USER="${ADMIN_USER:-admin}"
-ADMIN_PASS="${ADMIN_PASS:-C0lumnStore!}"
-ADMIN_HOST="${ADMIN_HOST:-%}"
-CEJ_USER="${CEJ_USER:-cej}"
-CEJ_PASS="${CEJ_PASS:-C0lumnStore!}"
-REP_USER="${REP_USER:-idbrep}"
-REP_PASS="${REP_PASS:-C0lumnStore!}"
-REP_HOST="${REP_HOST:-%}"
+CROSSENGINEJOIN_USER="${CROSSENGINEJOIN_USER:-cross_engine_joiner}"
+CROSSENGINEJOIN_PASS="${CROSSENGINEJOIN_PASS:-pwgen --numerals --capitalize --symbols --remove-chars="'\\" -1 32}"
+
 
 # Hostname Variables
 HOSTNAME="$(hostname -s)"
@@ -36,12 +31,6 @@ PM1_DNS="${PM1_DNS:-mcs1}"
 # Miscellaneous Variables
 RET=$'\n'
 
-# Copy Back MariaDB Folders
-rsync -ravz --delete /opt/var/lib/mysql /var/lib
-rsync -ravz --delete --exclude data2 --exclude data3 --exclude storagemanager /opt/var/lib/columnstore /var/lib
-rsync -ravz --delete /opt/etc/my.cnf.d /etc
-rsync -ravz --delete /opt/etc/columnstore /etc
-
 # CGroup Memory Allocation For Container
 mcsSetConfig SystemConfig CGroup "${CGROUP}"
 
@@ -51,14 +40,6 @@ ${RET}# Docker Settings
 server_id = ${SERVER_ID}
 collation_server = utf8_general_ci
 character_set_server = utf8
-log_bin = /var/lib/mysql/mariadb-bin
-log_bin_index = /var/lib/mysql/mariadb-bin.index
-#relay_log = /var/lib/mysql/mariadb-relay
-#relay_log_index = /var/lib/mysql/mariadb-relay.index
-#log_slave_updates = ON
-gtid_strict_mode = ON
-innodb_strict_mode = OFF
-log_error = /var/log/mariadb/columnstore/mariadb-error.log${RET}
 EOT
 
 # Storagemanager Configuration
@@ -90,18 +71,19 @@ if [[ "${PM1_DNS}" == "${HOSTNAME}"* || "${PM1_DNS}" == "${HOSTNAME}" ]]; then
         # Set Up Cross Engine Join User
         mariadb -e "
             GRANT SELECT, PROCESS
-            ON *.* TO '${CEJ_USER}'@'127.0.0.1'
-            IDENTIFIED BY '${CEJ_PASS}';
-            ALTER USER '${CEJ_USER}'@'127.0.0.1' PASSWORD EXPIRE NEVER;
+            ON *.* TO '${CROSSENGINEJOIN_USER}'@'127.0.0.1'
+            IDENTIFIED BY '${CROSSENGINEJOIN_PASS}';
+            ALTER USER '${CROSSENGINEJOIN_USER}'@'127.0.0.1' PASSWORD EXPIRE NEVER;
         "
         if [ $? -ne 0 ]; then
             echo 'ERROR: During cross engine join user creation.'
             exit 1
         fi
-        mcsSetConfig CrossEngineSupport User "${CEJ_USER}"
-        mcsSetConfig CrossEngineSupport Password "${CEJ_PASS}"
+        mcsSetConfig CrossEngineSupport User "${CROSSENGINEJOIN_USER}"
+        mcsSetConfig CrossEngineSupport Password "${CROSSENGINEJOIN_PASS}"
         mcsSetConfig CrossEngineSupport host "127.0.0.1"
 
+<<<<<<< HEAD
         # Set Up Admin User
         if [[ -n ${ADMIN_USER} ]] && [[ -n ${ADMIN_PASS} ]]; then
             mariadb -e "
@@ -134,6 +116,40 @@ if [[ "${PM1_DNS}" == "${HOSTNAME}"* || "${PM1_DNS}" == "${HOSTNAME}" ]]; then
             exit 1
         fi
         echo 'Replication user created'
+=======
+        # Set Up MaxScale User
+        mariadb -e "
+            GRANT BINLOG ADMIN,
+            READ_ONLY ADMIN,
+            RELOAD,
+            BINLOG MONITOR,
+            SLAVE MONITOR,
+            REPLICATION MASTER ADMIN,
+            REPLICATION SLAVE ADMIN,
+            REPLICATION SLAVE,
+            SHOW DATABASES
+            ON *.* TO '${MAX_USER}'@'${MAX_HOST}' IDENTIFIED BY '${MAX_PASS}';
+            ALTER USER '${MAX_USER}'@'${MAX_HOST}' PASSWORD EXPIRE NEVER;
+        "
+        if [ $? -ne 0 ]; then
+            echo "ERROR: Creating user '${MAX_USER}'@'${MAX_HOST}'."
+            exit 1
+        fi
+        mariadb -e "
+            GRANT SELECT ON mysql.columns_priv TO '${MAX_USER}'@'${MAX_HOST}';
+            GRANT SELECT ON mysql.db TO '${MAX_USER}'@'${MAX_HOST}';
+            GRANT SELECT ON mysql.procs_priv TO '${MAX_USER}'@'${MAX_HOST}';
+            GRANT SELECT ON mysql.proxies_priv TO '${MAX_USER}'@'${MAX_HOST}';
+            GRANT SELECT ON mysql.roles_mapping TO '${MAX_USER}'@'${MAX_HOST}';
+            GRANT SELECT ON mysql.tables_priv TO '${MAX_USER}'@'${MAX_HOST}';
+            GRANT SELECT ON mysql.user TO '${MAX_USER}'@'${MAX_HOST}';
+        "
+        if [ $? -ne 0 ]; then
+            echo "ERROR: Granting SELECT to '${MAX_USER}'@'${MAX_HOST}'."
+            exit 1
+        fi
+        echo 'MaxScale user created'
+>>>>>>> a5a089b (init copy)
 
         # Securing MariaDB Installation
         mariadb -e "
@@ -186,11 +202,6 @@ else
     /etc/init.d/mariadb stop
 
 fi
-
-# Standardize Log Ownership
-chown -R root:mysql /var/log/mariadb
-find /var/log/mariadb/ -type d -exec chmod g+ws {} \;
-rm -f /var/lib/mysql/buildkitsandbox.err
 
 # Mark Container Initialized
 touch "${IFLAG}"
